<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $people = [
            ['name' => 'Charlee', 'gender' => 'female'],
            ['name' => 'Jane', 'gender' => 'female'],
            ['name' => 'Isabelle', 'gender' => 'female'],
            ['name' => 'Isabell', 'gender' => 'female'],
            ['name' => 'Nathaly', 'gender' => 'female'],
            ['name' => 'Genevieve', 'gender' => 'female'],
            ['name' => 'Reina', 'gender' => 'female'],
            ['name' => 'Desiree', 'gender' => 'female'],
            ['name' => 'Alma', 'gender' => 'female'],
            ['name' => 'Maia', 'gender' => 'female'],
            ['name' => 'Zara', 'gender' => 'female'],
            ['name' => 'Sylvia', 'gender' => 'female'],
            ['name' => 'Kinsley', 'gender' => 'female'],
            ['name' => 'Arianna', 'gender' => 'female'],
            ['name' => 'Camryn', 'gender' => 'female'],
            ['name' => 'Briana', 'gender' => 'female'],
            ['name' => 'Eva', 'gender' => 'female'],
            ['name' => 'Audrina', 'gender' => 'female'],
            ['name' => 'Mara', 'gender' => 'female'],
            ['name' => 'Kristin', 'gender' => 'female'],
            ['name' => 'Amy', 'gender' => 'female'],
            ['name' => 'Catalina', 'gender' => 'female'],
            ['name' => 'Lyric', 'gender' => 'female'],
            ['name' => 'Kendra', 'gender' => 'female'],
            ['name' => 'Araceli', 'gender' => 'female'],
            ['name' => 'Lea', 'gender' => 'female'],
            ['name' => 'Ashleigh', 'gender' => 'female'],
            ['name' => 'Julia', 'gender' => 'female'],
            ['name' => 'Crystal', 'gender' => 'female'],
            ['name' => 'Isabella', 'gender' => 'female'],
            ['name' => 'Daphne', 'gender' => 'female'],
            ['name' => 'Jaelynn', 'gender' => 'female'],
            ['name' => 'Mila', 'gender' => 'female'],
            ['name' => 'Nevaeh', 'gender' => 'female'],
            ['name' => 'Theresa', 'gender' => 'female'],
            ['name' => 'Justice', 'gender' => 'female'],
            ['name' => 'Jasmine', 'gender' => 'female'],
            ['name' => 'Hanna', 'gender' => 'female'],
            ['name' => 'Bella', 'gender' => 'female'],
            ['name' => 'Kaliyah', 'gender' => 'female'],
            ['name' => 'Taryn', 'gender' => 'female'],
            ['name' => 'Isabela', 'gender' => 'female'],
            ['name' => 'Lizbeth', 'gender' => 'female'],
            ['name' => 'Thalia', 'gender' => 'female'],
            ['name' => 'Cecilia', 'gender' => 'female'],
            ['name' => 'Gianna', 'gender' => 'female'],
            ['name' => 'Cierra', 'gender' => 'female'],
            ['name' => 'Mariah', 'gender' => 'female'],
            ['name' => 'Lorelei', 'gender' => 'female'],
            ['name' => 'Wendy', 'gender' => 'female'],
            ['name' => 'Kimberly', 'gender' => 'female'],
            ['name' => 'Marie', 'gender' => 'female'],
            ['name' => 'Gretchen', 'gender' => 'female'],
            ['name' => 'April', 'gender' => 'female'],
            ['name' => 'Carolina', 'gender' => 'female'],
            ['name' => 'Josephine', 'gender' => 'female'],
            ['name' => 'Britney', 'gender' => 'female'],
            ['name' => 'Angela', 'gender' => 'female'],
            ['name' => 'Tiana', 'gender' => 'female'],
            ['name' => 'Saniyah', 'gender' => 'female'],
            ['name' => 'Keyla', 'gender' => 'female'],
            ['name' => 'Alena', 'gender' => 'female'],
            ['name' => 'Makena', 'gender' => 'female'],
            ['name' => 'Savannah', 'gender' => 'female'],
            ['name' => 'Jenna', 'gender' => 'female'],
            ['name' => 'Salma', 'gender' => 'female'],
            ['name' => 'Shyla', 'gender' => 'female'],
            ['name' => 'Nia', 'gender' => 'female'],
            ['name' => 'Selena', 'gender' => 'female'],
            ['name' => 'Azul', 'gender' => 'female'],
            ['name' => 'Abigail', 'gender' => 'female'],
            ['name' => 'Ann', 'gender' => 'female'],
            ['name' => 'Zariah', 'gender' => 'female'],
            ['name' => 'Mollie', 'gender' => 'female'],
            ['name' => 'Karla', 'gender' => 'female'],
            ['name' => 'Helen', 'gender' => 'female'],
            ['name' => 'Maritza', 'gender' => 'female'],
            ['name' => 'Adelyn', 'gender' => 'female'],
            ['name' => 'Anabella', 'gender' => 'female'],
            ['name' => 'Justine', 'gender' => 'female'],
            ['name' => 'Sanai', 'gender' => 'female'],
            ['name' => 'Kylee', 'gender' => 'female'],
            ['name' => 'Jaslene', 'gender' => 'female'],
            ['name' => 'Ella', 'gender' => 'female'],
            ['name' => 'Moriah', 'gender' => 'female'],
            ['name' => 'Scarlett', 'gender' => 'female'],
            ['name' => 'Laylah', 'gender' => 'female'],
            ['name' => 'Lilah', 'gender' => 'female'],
            ['name' => 'Andrea', 'gender' => 'female'],
            ['name' => 'Dixie', 'gender' => 'female'],
            ['name' => 'Kaitlyn', 'gender' => 'female'],
            ['name' => 'Giselle', 'gender' => 'female'],
            ['name' => 'June', 'gender' => 'female'],
            ['name' => 'Allison', 'gender' => 'female'],
            ['name' => 'Karley', 'gender' => 'female'],
            ['name' => 'Joslyn', 'gender' => 'female'],
            ['name' => 'Mireya', 'gender' => 'female'],
            ['name' => 'Cecelia', 'gender' => 'female'],
            ['name' => 'Karli', 'gender' => 'female'],
            ['name' => 'Nola', 'gender' => 'female'],
            ['name' => 'Nigel', 'gender' => 'male'],
            ['name' => 'Reed', 'gender' => 'male'],
            ['name' => 'Amare', 'gender' => 'male'],
            ['name' => 'Quinten', 'gender' => 'male'],
            ['name' => 'Morgan', 'gender' => 'male'],
            ['name' => 'Reginald', 'gender' => 'male'],
            ['name' => 'Ricky', 'gender' => 'male'],
            ['name' => 'Dario', 'gender' => 'male'],
            ['name' => 'John', 'gender' => 'male'],
            ['name' => 'Lamar', 'gender' => 'male'],
            ['name' => 'Keshawn', 'gender' => 'male'],
            ['name' => 'Callum', 'gender' => 'male'],
            ['name' => 'Brent', 'gender' => 'male'],
            ['name' => 'Jesse', 'gender' => 'male'],
            ['name' => 'Remington', 'gender' => 'male'],
            ['name' => 'Yael', 'gender' => 'male'],
            ['name' => 'Gavyn', 'gender' => 'male'],
            ['name' => 'Walter', 'gender' => 'male'],
            ['name' => 'Terry', 'gender' => 'male'],
            ['name' => 'Edward', 'gender' => 'male'],
            ['name' => 'Fabian', 'gender' => 'male'],
            ['name' => 'Jayvon', 'gender' => 'male'],
            ['name' => 'Zavier', 'gender' => 'male'],
            ['name' => 'Rishi', 'gender' => 'male'],
            ['name' => 'Noel', 'gender' => 'male'],
            ['name' => 'Jakob', 'gender' => 'male'],
            ['name' => 'Miguel', 'gender' => 'male'],
            ['name' => 'Rex', 'gender' => 'male'],
            ['name' => 'Marley', 'gender' => 'male'],
            ['name' => 'Damari', 'gender' => 'male'],
            ['name' => 'Winston', 'gender' => 'male'],
            ['name' => 'Boston', 'gender' => 'male'],
            ['name' => 'Jaeden', 'gender' => 'male'],
            ['name' => 'Trent', 'gender' => 'male'],
            ['name' => 'Parker', 'gender' => 'male'],
            ['name' => 'Myles', 'gender' => 'male'],
            ['name' => 'Rashad', 'gender' => 'male'],
            ['name' => 'Camron', 'gender' => 'male'],
            ['name' => 'Zayne', 'gender' => 'male'],
            ['name' => 'Kobe', 'gender' => 'male'],
            ['name' => 'Nico', 'gender' => 'male'],
            ['name' => 'Drake', 'gender' => 'male'],
            ['name' => 'Teagan', 'gender' => 'male'],
            ['name' => 'Lewis', 'gender' => 'male'],
            ['name' => 'Leo', 'gender' => 'male'],
            ['name' => 'Mitchell', 'gender' => 'male'],
            ['name' => 'Brice', 'gender' => 'male'],
            ['name' => 'Tyree', 'gender' => 'male'],
            ['name' => 'Arnav', 'gender' => 'male'],
            ['name' => 'Jair', 'gender' => 'male'],
            ['name' => 'Joseph', 'gender' => 'male'],
            ['name' => 'Jamar', 'gender' => 'male'],
            ['name' => 'Julius', 'gender' => 'male'],
            ['name' => 'Joey', 'gender' => 'male'],
            ['name' => 'Jay', 'gender' => 'male'],
            ['name' => 'Seth', 'gender' => 'male'],
            ['name' => 'Kale', 'gender' => 'male'],
            ['name' => 'Christian', 'gender' => 'male'],
            ['name' => 'Case', 'gender' => 'male'],
            ['name' => 'Garrett', 'gender' => 'male'],
            ['name' => 'Patrick', 'gender' => 'male'],
            ['name' => 'Yosef', 'gender' => 'male'],
            ['name' => 'Pierre', 'gender' => 'male'],
            ['name' => 'Roman', 'gender' => 'male'],
            ['name' => 'Raymond', 'gender' => 'male'],
            ['name' => 'Tucker', 'gender' => 'male'],
            ['name' => 'Mauricio', 'gender' => 'male'],
            ['name' => 'Jadyn', 'gender' => 'male'],
            ['name' => 'Easton', 'gender' => 'male'],
            ['name' => 'Michael', 'gender' => 'male'],
            ['name' => 'Aidan', 'gender' => 'male'],
            ['name' => 'Trace', 'gender' => 'male'],
            ['name' => 'Marlon', 'gender' => 'male'],
            ['name' => 'Jayden', 'gender' => 'male'],
            ['name' => 'Mario', 'gender' => 'male'],
            ['name' => 'Aydin', 'gender' => 'male'],
            ['name' => 'Savion', 'gender' => 'male'],
            ['name' => 'Leonidas', 'gender' => 'male'],
            ['name' => 'Davin', 'gender' => 'male'],
            ['name' => 'Jonas', 'gender' => 'male'],
            ['name' => 'Noe', 'gender' => 'male'],
            ['name' => 'Evan', 'gender' => 'male'],
            ['name' => 'Braden', 'gender' => 'male'],
            ['name' => 'Nikolai', 'gender' => 'male'],
            ['name' => 'Jasiah', 'gender' => 'male'],
            ['name' => 'Dashawn', 'gender' => 'male'],
            ['name' => 'Octavio', 'gender' => 'male'],
            ['name' => 'Ethen', 'gender' => 'male'],
            ['name' => 'Deven', 'gender' => 'male'],
            ['name' => 'Leonel', 'gender' => 'male'],
            ['name' => 'Kyson', 'gender' => 'male'],
            ['name' => 'Manuel', 'gender' => 'male'],
            ['name' => 'Darius', 'gender' => 'male'],
            ['name' => 'Marcus', 'gender' => 'male'],
            ['name' => 'Sincere', 'gender' => 'male'],
            ['name' => 'Cristofer', 'gender' => 'male'],
            ['name' => 'Simeon', 'gender' => 'male'],
            ['name' => 'Reid', 'gender' => 'male'],
            ['name' => 'Marcel', 'gender' => 'male'],
            ['name' => 'Trevor', 'gender' => 'male']
        ];

        $person = $this->faker->randomElement($people);

        return [
            'hex' => Str::random(11),
            'user_type_id' => rand(1,5),
            'first_name' => $person['name'],
            'last_name' => $this->faker->lastName(),
            'gender' => $person['gender'],
            'email' => $this->faker->unique()->safeEmail(),
            'email_verified_at' => now(),
            'phone' => $this->faker->phoneNumber(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Str::random(10),
            'active' => 1
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     *
     * @return static
     */
    public function unverified()
    {
        return $this->state(function (array $attributes) {
            return [
                'email_verified_at' => null,
            ];
        });
    }
}
